- name: declaring variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: accessing variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: declaring variable at file level
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: accessing variable at file level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: declaring variable at task level
  hosts: all
  connection: local
  tasks:
    - name: accessing variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: play.example.com

- name: declaring variable at inventory level
  hosts: all
  connection: local
  tasks:
    - name: accessing variable at inventory level
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: accessing FQDN
  hosts: all
  connection: local
  tasks:
    - name: accessing FQDN
      ansible.builtin.debug:
        msg: ansible Host name == {{ansible_fqdn}}

 - name: register
   hosts: all
   connection: local
   tasks:
     - name: access register
       ansible.builtin.shell: uptime
       register: out
     - name: Print Out
       ansible.buiiltin.debug:
         msg: "{{out}}"




