- name: declaring a variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: accessing variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declaring variable at task level
  hosts: all
  connection: local
  tasks:
    - name: accessing variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com