- name: declaring a variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: accessing variable
      ansible.builtin.debug:
        msg: URL == {{}}

