 - name: declaring variable at play level
   hosts: all
   vars:
     URL: play.example.com
    tasks:
      - name: accessing variable at play level
        ansible.builtin.debug:
          msg: {{URL}}
